name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Adjust if your default branch is named differently
  workflow_dispatch:

# Grant the workflow write access to contents
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository so the workflow can access your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (adjust the version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Use your preferred Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project using "npm run build"
      - name: Build project
        run: npm run build

      # Step 4x: Build the project using "npm run build"
      - name: list project
        run: ls -R

      # Step 5: Deploy the build output to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Update this path if your build output folder differs
